version: "3.7"

services:
  endpoint:
    build:
      context: Conduit
      dockerfile: Dockerfile
      target: Dev
    volumes:
      - ./Conduit:/var/app
    entrypoint: composer
    command:
      - serve
    ports:
      - 8080:8080

#  prod:
#    build:
#      context: Conduit
#      dockerfile: Dockerfile
#      target: Prod
#    ports:
#      - 9000:9000