version: "3.7"

services:
  endpoint:
    build:
      context: Conduit
      dockerfile: Dockerfile
      target: Dev
    volumes:
      - ./Conduit:/var/app
    entrypoint: composer
    command:
      - serve
    ports:
      - 9000:9000