version: "3.7"

services:
  conduit:
    build:
      context: Conduit
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./Conduit:/var/app
    ports:
      - 8080:8080
      - 9000:9000

  composer:
    build:
      context: Conduit
      dockerfile: Dockerfile
      target: Composer
    volumes:
      - ./Conduit:/var/app