version: "3.7"

services:
  conduit:
    build:
      context: Conduit
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./Conduit:/var/app
    ports:
      - 8080:8080
      - 9000:9000
    depends_on:
      - db

  composer:
    build:
      context: Conduit
      dockerfile: Dockerfile
      target: composer
    volumes:
      - ./Conduit:/var/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: conduit
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
