version: "3.7"

services:
  conduit:
    build:
      context: Conduit
      dockerfile: Dockerfile-dev
      target: development
    volumes:
      - ./Conduit:/var/app
    ports:
      - 8080:8080
      - 9000:9000

  composer:
    build:
      context: Conduit
      dockerfile: Dockerfile-dev
      target: composer
    tty: true
    volumes:
      - ./Conduit:/var/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
