name: BuildImage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: test image
      run: |
        docker image build --target=base-image --tag=multi-stage:base-image Conduit
        docker image build --target=test-package --tag=multi-stage:test-package Conduit

        docker container run --rm  multi-stage:test-package > res.txt

        grep -sq "OK (" res.txt
        if [[ $? -eq 0 ]]; then
          exit 0
        fi
        cat res.txt
        exit 1

    - name: docker login
      run: docker login docker.pkg.github.com -u shotanue -p $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_TO_PUSH_TO_PACKAGE_REGISTRY }}

    - name: build image
      run: |
        TAG="docker.pkg.github.com/${{ github.repository }}/bear-sunday-real-world-example-app:${SHA}"
        docker image build --target=ship --tag=${TAG} Conduit
      env:
        SHA: ${{ github.sha }}

    - name: push image
      env:
        SHA: ${{ github.sha }}
      run: docker push docker.pkg.github.com/${{ github.repository }}/bear-sunday-real-world-example-app:$SHA