name: BuildImage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: build image
        run: |
          TAG="docker.pkg.github.com/${{ github.repository }}/docker:${SHA}"

          docker image build --target=ship --tag=${TAG} Conduit
          docker image build --target=test --tag=multi-stage:test Conduit
        env:
          SHA: ${{ github.sha }}

      - name: test image
        run: |
          docker container run --rm  multi-stage:test
        env:
          SHA: ${{ github.sha }}

      - name: docker login
        run: docker login docker.pkg.github.com -u shotanue -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_TO_PUSH_TO_PACKAGE_REGISTRY }}

      - name: push image
        run: |
        TAG="docker.pkg.github.com/${{ github.repository }}/docker:${SHA}"
        docker push docker.pkg.github.com/${{ github.repository }}/docker:$SHA
        env:
          SHA: ${{ github.sha }}