name: Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: docker login
        run: docker login docker.pkg.github.com -u shotanue -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_TO_PUSH_TO_PACKAGE_REGISTRY }}
      - name: build image
        run: |
          docker image build --target=composer --tag=conduit-composer Conduit

      - name: test image
        run: |
          docker container run --rm -v $(pwd)/Conduit:/var/app conduit-composer install
          docker container run --rm -v $(pwd)/Conduit:/var/app conduit-composer test
